export const EVENT_FAMILIES = {
  homepage: [
    "homepage_open",
    "homepage_search_focus",
    "homepage_search_submit",
    "homepage_quick_chip_clicked",
    "homepage_counter_clicked",
    "homepage_action_card_clicked",
    "homepage_recent_profile_clicked",
    "homepage_source_gap_clicked",
    "homepage_packet_funnel_viewed",
    "homepage_packet_started",
    "homepage_watchlist_cta_clicked",
    "homepage_package_interest_clicked",
    "homepage_trust_box_clicked",
  ],
  navigation: [
    "page_view",
    "nav_click",
    "footer_click",
    "internal_link_click",
    "external_source_click",
    "next_action_click",
    "next_action_clicked",
    "command_palette_open",
  ],
  search: [
    "search_page_open",
    "search_query_started",
    "search_query_submitted",
    "search_filter_used",
    "search_sort_changed",
    "search_result_clicked",
    "search_no_results",
    "global_search_started",
    "global_search_submitted",
    "global_search_result_clicked",
    "official_search",
    "race_search",
    "issue_search",
    "county_search",
    "no_results_seen",
    "filter_used",
    "sort_changed",
    "saved_search_created",
    "command_search_input",
    "command_result_clicked",
    "command_action_clicked",
    "command_no_result",
  ],
  profiles: [
    "profile_open",
    "profile_section_viewed",
    "source_trail_opened",
    "vote_table_opened",
    "funding_table_opened",
    "timeline_opened",
    "red_flag_opened",
    "correction_clicked",
    "correction_clicked_from_profile",
    "profile_share_clicked",
    "profile_watch_clicked",
    "profile_compare_clicked",
    "source_clicked_from_profile",
    "submit_source_clicked_from_profile",
  ],
  data_intake: [
    "form_started",
    "form_step_completed",
    "form_submitted",
    "form_submit_failed",
    "form_abandoned",
    "source_submit_started",
    "source_url_entered",
    "source_target_selected",
    "source_target_type_selected",
    "source_target_entered",
    "source_packet_previewed",
    "source_submit_completed",
    "source_submit_failed",
    "correction_submit_started",
    "correction_submit_completed",
    "correction_started",
    "correction_completed",
    "privacy_request_submitted",
    "packet_builder_started",
    "packet_type_selected",
    "packet_source_added",
    "packet_generated",
    "packet_copied",
    "packet_submitted",
    "packet_saved",
    "packet_account_prompt_clicked",
    "packet_watch_clicked",
    "packet_builder_completed",
    "records_request_started",
    "records_request_generated",
    "records_request_copied",
    "records_request_saved",
    "records_request_status_changed",
    "records_request_account_prompt_clicked",
    "records_request_created",
    "attachment_uploaded",
    "investor_interest_submitted",
    "partner_interest_submitted",
    "broken_link_reported",
  ],
  engagement: [
    "feedback_vote_clicked",
    "useful_vote_clicked",
    "needs_source_vote_clicked",
    "source_quality_vote_clicked",
    "public_question_copied",
    "source_snippet_copied",
    "share_menu_open",
    "share_copy_link",
    "share_copy_snippet",
    "share_snippet_copied",
    "native_share_clicked",
    "social_share_clicked",
    "watch_button_clicked",
    "watch_reason_selected",
    "watchlist_created",
    "watchlist_add",
    "watchlist_remove",
    "anonymous_watch_intent_created",
    "anonymous_watch_converted",
    "digest_signup",
    "account_prompt_seen",
    "account_prompt_clicked",
    "feedback_vote_changed",
    "feedback_rollup_updated",
    "next_action_impression",
    "next_action_dismissed",
    "next_action_converted",
  ],
  dashboard: [
    "dashboard_open",
    "dashboard_module_open",
    "dashboard_next_action_clicked",
    "watchlist_open",
    "packet_open",
    "dashboard_packet_started",
    "dashboard_submission_opened",
    "saved_search_open",
    "digest_settings_changed",
    "interest_profile_reset",
    "privacy_page_open",
    "privacy_control_used",
  ],
  admin: [
    "admin_open",
    "admin_module_open",
    "admin_form_opened",
    "admin_form_status_changed",
    "admin_source_review_started",
    "admin_source_review_completed",
    "ai_source_review_started",
    "ai_source_review_completed",
    "ai_source_review_failed",
    "ai_suggestion_accepted",
    "ai_suggestion_rejected",
    "ai_safety_flag_triggered",
    "source_admin_review_started",
    "source_admin_status_changed",
    "source_attached_to_entity",
    "source_rejected",
    "source_marked_duplicate",
    "admin_profile_updated",
    "admin_correction_resolved",
    "correction_admin_resolved",
    "admin_safety_override",
    "admin_data_health_opened",
    "data_source_registry_open",
    "import_run_started",
    "import_run_completed",
    "import_run_failed",
    "import_error_logged",
    "data_source_missing_key",
    "admin_monetization_opened",
    "admin_audit_log_opened",
    "seo_audit_opened",
    "admin_story_published",
    "admin_wire_item_quarantined",
    "admin_duplicate_merged",
  ],
  monetization_readiness: [
    "package_card_viewed",
    "package_page_open",
    "package_interest_clicked",
    "package_interest_clicked_from_profile",
    "package_interest_clicked_from_dashboard",
    "package_interest_submitted",
    "package_interest_abandoned",
    "package_faq_open",
    "free_tool_clicked_from_package",
    "monetization_dashboard_open",
    "package_readiness_viewed",
    "readiness_recommendation_generated",
    "feature_flag_evaluated",
    "pricing_experiment_viewed",
    "pricing_variant_assigned",
    "pricing_variant_viewed",
    "pricing_cta_clicked",
    "beta_access_requested",
    "beta_invite_sent",
    "pricing_interest_clicked",
    "waitlist_joined",
    "research_request_started",
    "research_request_completed",
    "checkout_started",
    "checkout_completed",
  ],
  diagnostics: [
    "scroll_depth",
    "time_spent",
    "heatmap_click",
    "exit",
    "download",
    "route_depth",
    "sitemap_generated",
    "safety_warning_triggered",
  ],
} as const;

export type EventFamily = keyof typeof EVENT_FAMILIES;
export type AnalyticsEventName = (typeof EVENT_FAMILIES)[EventFamily][number];

export const ANALYTICS_EVENT_NAMES = new Set<string>(
  Object.values(EVENT_FAMILIES).flatMap((events) => [...events]),
);

export const EVENT_FAMILY_BY_NAME = Object.fromEntries(
  Object.entries(EVENT_FAMILIES).flatMap(([family, events]) =>
    events.map((eventName) => [eventName, family]),
  ),
) as Record<AnalyticsEventName, EventFamily>;

const EVENT_ALIASES: Record<string, AnalyticsEventName> = {
  button_click: "next_action_click",
  next_action_clicked: "next_action_clicked",
  search: "global_search_submitted",
  profile_view: "profile_open",
  topic_view: "profile_section_viewed",
  issue_view: "issue_search",
  county_view: "county_search",
  share: "share_snippet_copied",
  packet_build: "packet_builder_completed",
  packet_creation: "packet_builder_completed",
  packet_generated: "packet_generated",
  packet_saved: "packet_saved",
  packet_submitted: "packet_submitted",
  records_request_generated: "records_request_generated",
  records_request_saved: "records_request_saved",
  submit_source: "source_submit_completed",
  source_submission: "source_submit_completed",
  request_review: "correction_clicked",
  correction_clicked_from_profile: "correction_clicked_from_profile",
  correction_started: "correction_started",
  correction_completed: "correction_completed",
  privacy_request_submitted: "privacy_request_submitted",
  form_complete: "form_submitted",
  form_error: "form_submit_failed",
  broken_link: "broken_link_reported",
  email_signup: "digest_signup",
  watch_record: "profile_watch_clicked",
  watch_button_clicked: "profile_watch_clicked",
  watch_reason_selected: "profile_watch_clicked",
  watchlist_created: "watchlist_add",
  watchlist_creation: "watchlist_add",
  anonymous_watch_intent_created: "profile_watch_clicked",
  anonymous_watch_converted: "watchlist_add",
  official_follow: "profile_watch_clicked",
  race_follow: "watchlist_add",
  source_clicked_from_profile: "source_clicked_from_profile",
  submit_source_clicked_from_profile: "submit_source_clicked_from_profile",
  package_interest_clicked_from_profile: "package_interest_clicked_from_profile",
  admin_dashboard_opened: "admin_open",
};

const LEGACY_EVENT_NAMES: Record<string, string> = {
  nav_click: "button_click",
  footer_click: "button_click",
  internal_link_click: "button_click",
  external_source_click: "button_click",
  next_action_click: "button_click",
  next_action_clicked: "button_click",
  command_palette_open: "button_click",
  command_search_input: "search",
  command_result_clicked: "search",
  command_action_clicked: "button_click",
  command_no_result: "search",
  search_page_open: "search",
  search_query_started: "search",
  search_query_submitted: "search",
  search_filter_used: "button_click",
  search_sort_changed: "button_click",
  search_result_clicked: "search",
  search_no_results: "search",
  global_search_started: "search",
  global_search_submitted: "search",
  global_search_result_clicked: "search",
  official_search: "search",
  race_search: "search",
  issue_search: "search",
  county_search: "search",
  no_results_seen: "search",
  filter_used: "button_click",
  sort_changed: "button_click",
  saved_search_created: "button_click",
  profile_open: "profile_view",
  profile_section_viewed: "topic_view",
  source_trail_opened: "button_click",
  vote_table_opened: "button_click",
  funding_table_opened: "button_click",
  timeline_opened: "button_click",
  red_flag_opened: "button_click",
  correction_clicked: "request_review",
  correction_clicked_from_profile: "request_review",
  profile_share_clicked: "share",
  profile_watch_clicked: "watch_record",
  profile_compare_clicked: "button_click",
  source_clicked_from_profile: "button_click",
  submit_source_clicked_from_profile: "submit_source",
  source_submit_started: "submit_source",
  source_url_entered: "submit_source",
  source_target_selected: "submit_source",
  source_target_type_selected: "submit_source",
  source_target_entered: "submit_source",
  source_packet_previewed: "packet_build",
  source_submit_completed: "source_submission",
  source_submit_failed: "submit_source",
  form_started: "button_click",
  form_step_completed: "button_click",
  form_submitted: "source_submission",
  form_submit_failed: "submit_source",
  form_abandoned: "button_click",
  correction_submit_started: "request_review",
  correction_submit_completed: "request_review",
  correction_started: "request_review",
  correction_completed: "request_review",
  privacy_request_submitted: "request_review",
  packet_builder_started: "packet_build",
  packet_type_selected: "button_click",
  packet_source_added: "packet_build",
  packet_generated: "packet_creation",
  packet_copied: "share",
  packet_submitted: "source_submission",
  packet_saved: "packet_creation",
  packet_account_prompt_clicked: "button_click",
  packet_watch_clicked: "watch_record",
  packet_builder_completed: "packet_creation",
  records_request_started: "packet_creation",
  records_request_generated: "packet_creation",
  records_request_copied: "share",
  records_request_saved: "packet_creation",
  records_request_status_changed: "button_click",
  records_request_account_prompt_clicked: "button_click",
  records_request_created: "packet_creation",
  attachment_uploaded: "source_submission",
  investor_interest_submitted: "request_review",
  partner_interest_submitted: "request_review",
  broken_link_reported: "request_review",
  feedback_vote_clicked: "button_click",
  useful_vote_clicked: "button_click",
  needs_source_vote_clicked: "button_click",
  source_quality_vote_clicked: "button_click",
  public_question_copied: "share",
  source_snippet_copied: "share",
  share_menu_open: "share",
  share_copy_link: "share",
  share_copy_snippet: "share",
  share_snippet_copied: "share",
  native_share_clicked: "share",
  social_share_clicked: "share",
  watchlist_add: "watchlist_creation",
  watchlist_remove: "button_click",
  watch_button_clicked: "watch_record",
  watch_reason_selected: "watch_record",
  watchlist_created: "watchlist_creation",
  anonymous_watch_intent_created: "watch_record",
  anonymous_watch_converted: "watchlist_creation",
  feedback_vote_changed: "button_click",
  feedback_rollup_updated: "button_click",
  next_action_impression: "button_click",
  next_action_dismissed: "button_click",
  next_action_converted: "button_click",
  digest_signup: "email_signup",
  account_prompt_seen: "button_click",
  account_prompt_clicked: "button_click",
  dashboard_open: "button_click",
  dashboard_module_open: "button_click",
  dashboard_next_action_clicked: "button_click",
  watchlist_open: "button_click",
  packet_open: "button_click",
  dashboard_packet_started: "packet_build",
  dashboard_submission_opened: "button_click",
  saved_search_open: "button_click",
  digest_settings_changed: "button_click",
  interest_profile_reset: "button_click",
  privacy_page_open: "button_click",
  privacy_control_used: "button_click",
  admin_open: "admin_dashboard_opened",
  admin_module_open: "admin_dashboard_opened",
  admin_form_opened: "admin_dashboard_opened",
  admin_form_status_changed: "button_click",
  admin_source_review_started: "button_click",
  admin_source_review_completed: "button_click",
  ai_source_review_started: "button_click",
  ai_source_review_completed: "button_click",
  ai_source_review_failed: "button_click",
  ai_suggestion_accepted: "button_click",
  ai_suggestion_rejected: "button_click",
  ai_safety_flag_triggered: "button_click",
  source_admin_review_started: "button_click",
  source_admin_status_changed: "button_click",
  source_attached_to_entity: "source_submission",
  source_rejected: "button_click",
  source_marked_duplicate: "button_click",
  admin_profile_updated: "button_click",
  admin_correction_resolved: "button_click",
  correction_admin_resolved: "button_click",
  admin_safety_override: "button_click",
  admin_data_health_opened: "button_click",
  data_source_registry_open: "admin_dashboard_opened",
  import_run_started: "button_click",
  import_run_completed: "button_click",
  import_run_failed: "button_click",
  import_error_logged: "button_click",
  data_source_missing_key: "button_click",
  admin_monetization_opened: "button_click",
  admin_audit_log_opened: "button_click",
  seo_audit_opened: "admin_dashboard_opened",
  admin_story_published: "button_click",
  admin_wire_item_quarantined: "button_click",
  admin_duplicate_merged: "button_click",
  package_card_viewed: "button_click",
  package_interest_clicked: "request_review",
  package_interest_clicked_from_profile: "request_review",
  package_interest_clicked_from_dashboard: "request_review",
  package_interest_submitted: "request_review",
  homepage_open: "page_view",
  homepage_search_focus: "search",
  homepage_search_submit: "search",
  homepage_quick_chip_clicked: "button_click",
  homepage_counter_clicked: "button_click",
  homepage_action_card_clicked: "button_click",
  homepage_recent_profile_clicked: "profile_view",
  homepage_source_gap_clicked: "submit_source",
  homepage_packet_funnel_viewed: "button_click",
  homepage_packet_started: "packet_build",
  homepage_watchlist_cta_clicked: "watchlist_creation",
  homepage_package_interest_clicked: "request_review",
  homepage_trust_box_clicked: "button_click",
  feature_flag_evaluated: "button_click",
  pricing_experiment_viewed: "button_click",
  pricing_variant_assigned: "button_click",
  pricing_variant_viewed: "button_click",
  pricing_cta_clicked: "request_review",
  beta_access_requested: "request_review",
  beta_invite_sent: "button_click",
  pricing_interest_clicked: "request_review",
  waitlist_joined: "email_signup",
  research_request_started: "request_review",
  research_request_completed: "request_review",
  safety_warning_triggered: "button_click",
};

export const INTEREST_FAMILIES = [
  "geography",
  "office_type",
  "issue",
  "source_type",
  "engagement_type",
  "data_product",
  "monetization_signal",
] as const;

export type InterestFamily = (typeof INTEREST_FAMILIES)[number];

export const INTEREST_WEIGHT_BY_EVENT: Record<string, number> = {
  page_view: 1,
  profile_section_viewed: 1,
  profile_open: 3,
  global_search_submitted: 4,
  official_search: 4,
  race_search: 4,
  issue_search: 4,
  county_search: 4,
  external_source_click: 4,
  feedback_vote_clicked: 5,
  useful_vote_clicked: 5,
  needs_source_vote_clicked: 5,
  source_quality_vote_clicked: 5,
  source_url_entered: 4,
  source_clicked_from_profile: 4,
  source_target_type_selected: 4,
  source_target_entered: 4,
  source_packet_previewed: 6,
  share_snippet_copied: 6,
  native_share_clicked: 6,
  social_share_clicked: 6,
  profile_share_clicked: 6,
  profile_watch_clicked: 8,
  watch_button_clicked: 6,
  watch_reason_selected: 7,
  watchlist_created: 9,
  submit_source_clicked_from_profile: 7,
  watchlist_add: 8,
  anonymous_watch_intent_created: 8,
  anonymous_watch_converted: 10,
  source_submit_completed: 10,
  correction_completed: 9,
  privacy_request_submitted: 6,
  source_attached_to_entity: 12,
  share_copy_link: 5,
  share_copy_snippet: 6,
  share_menu_open: 2,
  form_submitted: 8,
  investor_interest_submitted: 12,
  partner_interest_submitted: 12,
  broken_link_reported: 7,
  packet_generated: 8,
  packet_saved: 10,
  packet_submitted: 12,
  packet_copied: 6,
  packet_builder_completed: 10,
  records_request_generated: 8,
  records_request_saved: 10,
  records_request_copied: 6,
  records_request_status_changed: 6,
  package_interest_clicked: 12,
  package_interest_clicked_from_profile: 12,
  package_interest_clicked_from_dashboard: 12,
  package_interest_submitted: 12,
  dashboard_next_action_clicked: 4,
  dashboard_packet_started: 8,
  dashboard_submission_opened: 4,
  interest_profile_reset: 2,
  privacy_control_used: 2,
  pricing_experiment_viewed: 4,
  pricing_variant_assigned: 5,
  pricing_variant_viewed: 5,
  pricing_cta_clicked: 10,
  beta_access_requested: 15,
  account_prompt_clicked: 15,
  feedback_vote_changed: 6,
  feedback_rollup_updated: 3,
  next_action_impression: 1,
  next_action_dismissed: 1,
  next_action_converted: 8,
  homepage_open: 1,
  homepage_search_focus: 2,
  homepage_search_submit: 6,
  homepage_quick_chip_clicked: 4,
  homepage_counter_clicked: 3,
  homepage_action_card_clicked: 5,
  homepage_recent_profile_clicked: 6,
  homepage_source_gap_clicked: 8,
  homepage_packet_funnel_viewed: 2,
  homepage_packet_started: 10,
  homepage_watchlist_cta_clicked: 10,
  homepage_package_interest_clicked: 12,
  homepage_trust_box_clicked: 3,
};

export function canonicalEventName(value: string | null | undefined): string | null {
  const normalized = value?.trim().toLowerCase().replace(/[^a-z0-9_:-]/g, "_").replace(/_+/g, "_") ?? "";
  if (!normalized) return null;
  if (ANALYTICS_EVENT_NAMES.has(normalized)) return normalized;
  return EVENT_ALIASES[normalized] ?? null;
}

export function eventFamilyFor(eventName: string) {
  const canonical = canonicalEventName(eventName);
  return canonical ? EVENT_FAMILY_BY_NAME[canonical as AnalyticsEventName] ?? null : null;
}

export function legacyEventNameForAnalytics(eventName: string) {
  const canonical = canonicalEventName(eventName);
  if (!canonical) return null;
  return LEGACY_EVENT_NAMES[canonical] ?? canonical;
}
