-- RepWatchr Marion County community pulse.
-- Additive only: this migration does not alter profiles, members, or prior vote data.
-- The public site reads and writes through a server-only service-role route.

create table if not exists public.race_community_polls (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  question text not null,
  status text not null default 'draft',
  opens_at timestamptz,
  closes_at timestamptz,
  minimum_sample integer not null default 25,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint race_community_polls_slug_length
    check (char_length(slug) between 3 and 120),
  constraint race_community_polls_question_length
    check (char_length(question) between 10 and 240),
  constraint race_community_polls_status
    check (status in ('draft', 'open', 'closed')),
  constraint race_community_polls_sample_range
    check (minimum_sample between 10 and 500),
  constraint race_community_polls_time_order
    check (opens_at is null or closes_at is null or opens_at < closes_at)
);

create table if not exists public.race_community_poll_options (
  poll_id bigint not null
    references public.race_community_polls(id) on delete cascade,
  option_id text not null,
  label text not null,
  display_order smallint not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  primary key (poll_id, option_id),
  constraint race_community_poll_options_id_length
    check (char_length(option_id) between 3 and 120),
  constraint race_community_poll_options_label_length
    check (char_length(label) between 2 and 160),
  constraint race_community_poll_options_order_positive
    check (display_order > 0),
  constraint race_community_poll_options_unique_order
    unique (poll_id, display_order)
);

create table if not exists public.race_community_poll_responses (
  poll_id bigint not null
    references public.race_community_polls(id) on delete cascade,
  user_id uuid not null
    references auth.users(id) on delete cascade,
  option_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (poll_id, user_id),
  constraint race_community_poll_responses_valid_option
    foreign key (poll_id, option_id)
    references public.race_community_poll_options(poll_id, option_id)
    on update cascade
    on delete restrict
);

create index if not exists race_community_poll_responses_tally_idx
  on public.race_community_poll_responses (poll_id, option_id);

create index if not exists race_community_poll_responses_user_idx
  on public.race_community_poll_responses (user_id);

alter table public.race_community_polls enable row level security;
alter table public.race_community_polls force row level security;
alter table public.race_community_poll_options enable row level security;
alter table public.race_community_poll_options force row level security;
alter table public.race_community_poll_responses enable row level security;
alter table public.race_community_poll_responses force row level security;

revoke all on table public.race_community_polls
  from public, anon, authenticated;
revoke all on table public.race_community_poll_options
  from public, anon, authenticated;
revoke all on table public.race_community_poll_responses
  from public, anon, authenticated;
revoke all on sequence public.race_community_polls_id_seq
  from public, anon, authenticated;

grant select, insert, update, delete
  on table public.race_community_polls to service_role;
grant select, insert, update, delete
  on table public.race_community_poll_options to service_role;
grant select, insert, update, delete
  on table public.race_community_poll_responses to service_role;
grant usage, select
  on sequence public.race_community_polls_id_seq to service_role;

create or replace view public.race_community_poll_totals
with (security_invoker = true)
as
select
  poll_id,
  option_id,
  count(*)::bigint as votes,
  max(updated_at) as as_of
from public.race_community_poll_responses
group by poll_id, option_id;

revoke all on table public.race_community_poll_totals
  from public, anon, authenticated;
grant select on table public.race_community_poll_totals to service_role;

comment on table public.race_community_polls is
  'Server-managed RepWatchr community pulses. Not scientific or official election polling.';
comment on table public.race_community_poll_responses is
  'One current response per poll and authenticated account. No geography, provider, email, IP, or bot token is stored.';
comment on view public.race_community_poll_totals is
  'Service-role-only aggregate response totals for public display after each poll privacy threshold is met.';

insert into public.race_community_polls (
  slug,
  question,
  status,
  opens_at,
  closes_at,
  minimum_sample,
  updated_at
)
values (
  'marion-county-judge-2026',
  'If the election were today, who would you support?',
  'open',
  now(),
  '2026-11-04 02:00:00+00',
  25,
  now()
)
on conflict (slug) do update
set
  question = excluded.question,
  status = excluded.status,
  closes_at = excluded.closes_at,
  minimum_sample = excluded.minimum_sample,
  updated_at = now();

insert into public.race_community_poll_options (
  poll_id,
  option_id,
  label,
  display_order,
  active
)
select
  poll.id,
  option.option_id,
  option.label,
  option.display_order,
  true
from public.race_community_polls as poll
cross join (
  values
    ('dina-k-carroll', 'Dina K. Carroll', 1::smallint),
    ('leward-j-lafleur-ii', 'Leward J. LaFleur II', 2::smallint)
) as option(option_id, label, display_order)
where poll.slug = 'marion-county-judge-2026'
on conflict (poll_id, option_id) do update
set
  label = excluded.label,
  display_order = excluded.display_order,
  active = true;
